<?php

/**
 * LUM_StyleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_StyleTable extends PluginLUM_StyleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_StyleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Style');
    }
}