<?php

/**
 * LUM_NotifiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_NotifiTable extends PluginLUM_NotifiTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_NotifiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Notifi');
    }
}