<?php

/**
 * LUM_UserBookmarkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_UserBookmarkTable extends PluginLUM_UserBookmarkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_UserBookmarkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_UserBookmark');
    }
}