<?php

/**
 * LUM_CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_CommentTable extends PluginLUM_CommentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_CommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Comment');
    }
}