<?php

/**
 * LUM_UserDiscussionWatchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_UserDiscussionWatchTable extends PluginLUM_UserDiscussionWatchTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_UserDiscussionWatchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_UserDiscussionWatch');
    }
}