<?php

/**
 * LUM_PollDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_PollDataTable extends PluginLUM_PollDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_PollDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_PollData');
    }
}