<?php

/**
 * LUM_DiscussionTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_DiscussionTagsTable extends PluginLUM_DiscussionTagsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_DiscussionTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_DiscussionTags');
    }
}