<?php

/**
 * LUM_DiscussionUserWhisperFromTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_DiscussionUserWhisperFromTable extends PluginLUM_DiscussionUserWhisperFromTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_DiscussionUserWhisperFromTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_DiscussionUserWhisperFrom');
    }
}