<?php

/**
 * LUM_AttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_AttachmentTable extends PluginLUM_AttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_AttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Attachment');
    }
}