<?php

/**
 * LUM_LabelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_LabelTable extends PluginLUM_LabelTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_LabelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Label');
    }
}