<?php

/**
 * LUM_Entity_PlaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_Entity_PlaceTable extends PluginLUM_Entity_PlaceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_Entity_PlaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Entity_Place');
    }
}