<?php

/**
 * LUM_NotifyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_NotifyTable extends PluginLUM_NotifyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_NotifyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Notify');
    }
}