<?php

/**
 * LUM_CategoryRoleBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_CategoryRoleBlockTable extends PluginLUM_CategoryRoleBlockTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_CategoryRoleBlockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_CategoryRoleBlock');
    }
}