<?php

/**
 * LUM_CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_CategoryTable extends PluginLUM_CategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Category');
    }
}