<?php

/**
 * LUM_EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_EventTable extends PluginLUM_EventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Event');
    }
}