<?php

/**
 * LUM_CategoryBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_CategoryBlockTable extends PluginLUM_CategoryBlockTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_CategoryBlockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_CategoryBlock');
    }
}