<?php

/**
 * LUM_CategoryBlock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zeitgeist.musiques-incongrues.net
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LUM_CategoryBlock extends PluginLUM_CategoryBlock
{
}
