<?php

/**
 * LUM_PollTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_PollTable extends PluginLUM_PollTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_PollTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Poll');
    }
}